'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System

Namespace TreeViewReport

    ''' <summary>
    '''   A strongly-typed resource class, for looking up localized strings, etc.
    ''' </summary>
    ' This class was auto-generated by the StronglyTypedResourceBuilder
    ' class via a tool like ResGen or Visual Studio.
    ' To add or remove a member, edit your .ResX file then rerun ResGen
    ' with the /str option, or rebuild your VS project.
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")>
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Class PrintRibbonControllerResources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
        End Sub

        ''' <summary>
        '''   Returns the cached ResourceManager instance used by this class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared ReadOnly Property ResourceManager As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(TreeViewReport.PrintRibbonControllerResources.resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TreeViewReport.PrintRibbonControllerResources", GetType(TreeViewReport.PrintRibbonControllerResources).Assembly)
                    TreeViewReport.PrintRibbonControllerResources.resourceMan = temp
                End If

                Return TreeViewReport.PrintRibbonControllerResources.resourceMan
            End Get
        End Property

        ''' <summary>
        '''   Overrides the current thread's CurrentUICulture property for all
        '''   resource lookups using this strongly typed resource class.
        ''' </summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Friend Shared Property Culture As Global.System.Globalization.CultureInfo
            Get
                Return TreeViewReport.PrintRibbonControllerResources.resourceCulture
            End Get

            Set(ByVal value As Global.System.Globalization.CultureInfo)
                TreeViewReport.PrintRibbonControllerResources.resourceCulture = value
            End Set
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreview As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreviewLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Customize As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Customize", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_CustomizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Document As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Document", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMap As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMapLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHF As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHFLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFile", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtm As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtmLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMht", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXls", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsx", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ExportXlsxLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackground As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackground", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FillBackgroundLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Find As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Find", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_FindLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_FindLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_HandTool As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_HandTool", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Magnifier As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Magnifier", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePages As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePagesLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Open As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Open", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_OpenLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMargins As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMargins", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsModerate As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNarrow As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNormal As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsWide As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientation As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLandscape As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationPortrait As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PageSetupDialog As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A3 As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A4 As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A5 As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A6 As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Executive As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Legal As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Letter As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Tabloid As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSize As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSize", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PaperSizeLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Parameters As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Parameters", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ParametersLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Pointer As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Pointer", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Print As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Print", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirect As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirectLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetup As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetupLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Save As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Save", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SaveLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Scale As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Scale", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ScaleLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsv As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsv", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendCsvLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFile As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFile", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendFileLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphic As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphicLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMht As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMht", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendMhtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdf As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdf", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendPdfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtf As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtf", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendRtfLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxt As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxt", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendTxtLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXls As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXls", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsx As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsx", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsxLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_SendXlsxLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPage As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPageLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Thumbnails As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Thumbnails", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ThumbnailsLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ThumbnailsLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Watermark As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Watermark", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_WatermarkLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_Zoom As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_Zoom", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomIn As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomInLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOut As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property

        ''' <summary>
        '''   Looks up a localized resource of type System.Drawing.Bitmap.
        ''' </summary>
        Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOutLarge As System.Drawing.Bitmap
            Get
                Dim obj As Object = TreeViewReport.PrintRibbonControllerResources.ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", TreeViewReport.PrintRibbonControllerResources.resourceCulture)
                Return CType((obj), System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
