Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace TreeViewReport


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
	Friend Class PrintRibbonControllerResources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("PrintRibbonControllerResources", GetType(PrintRibbonControllerResources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreview() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreviewLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Customize() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Customize", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_CustomizeLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Document() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Document", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMap() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMapLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHF() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHFLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsvLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportFile() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportFile", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportFileLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphic() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphicLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtm() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtmLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportMht() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportMht", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportMhtLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdf() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdfLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtf() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtfLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxtLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportXls() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXls", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsx", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsxLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsxLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_FillBackground() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FillBackground", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_FillBackgroundLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Find() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Find", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_FindLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FindLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_HandTool() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_HandTool", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Magnifier() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Magnifier", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePages() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePagesLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Open() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Open", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_OpenLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageMargins() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMargins", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsModerate() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNarrow() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNormal() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsWide() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientation() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLandscape() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationPortrait() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PageSetupDialog() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A3() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A4() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A5() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A6() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Executive() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Legal() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Letter() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Tabloid() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperSize() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperSize", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PaperSizeLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Parameters() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Parameters", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ParametersLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Pointer() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Pointer", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Print() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Print", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirect() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirectLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PrintLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetup() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetupLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Save() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Save", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SaveLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Scale() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Scale", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ScaleLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendCsv() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendCsv", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendCsvLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendFile() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendFile", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendFileLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphic() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphicLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendMht() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendMht", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendMhtLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendPdf() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendPdf", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendPdfLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendRtf() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendRtf", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendRtfLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendTxt() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendTxt", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendTxtLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendXls() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXls", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsx() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXlsx", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsxLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXlsxLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPage() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPageLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPage() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPageLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPage() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPageLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPage() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPageLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Thumbnails() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Thumbnails", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ThumbnailsLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ThumbnailsLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Watermark() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Watermark", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_WatermarkLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_Zoom() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Zoom", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ZoomIn() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ZoomInLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ZoomLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOut() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized resource of type System.Drawing.Bitmap.
		''' </summary>
		Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOutLarge() As System.Drawing.Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", resourceCulture)
				Return (DirectCast(obj, System.Drawing.Bitmap))
			End Get
		End Property
	End Class
End Namespace
